MS_Project/ProjectSettings/TagManager.asset
=> Add: 敵のレイヤー(マージテスト)

MS_Project/Assets/Prefabs.meta, MS_Project/Assets/Prefabs/Enemy.meta, MS_Project/Assets/Prefabs/Enemy/ProtoEnemy.prefab, MS_Project/Assets/Prefabs/Enemy/ProtoEnemy.prefab.meta, MS_Project/Assets/Scenes/SampleScene.unity
=> Add: 簡易な敵実装

MS_Project/Assets/Resources/Player/PAttack_Clip.anim, MS_Project/Assets/Resources/Player/PAttack_Clip.anim.meta
=> Add: プレイヤー攻撃アニメーションイベント

MS_Project/Assets/Resources/Player/PAttack_Clip.anim, MS_Project/Assets/Resources/Player/Sprite_ACont.controller, MS_Project/Assets/Scenes/SampleScene.unity, MS_Project/Assets/Scripts/Manager/Input/PlayerInputManager.cs.meta
=> Fix: InputManagerを優先的に実行させる

MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/PlayerAnimManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerIdleState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerWalkState.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Manager/Input/PlayerInputManager.cs
=> Update: 敵にダメージを与える処理

MS_Project/Assets/Scripts/Character/Enemy/ProtoEnemyController.cs, MS_Project/Assets/Scripts/Character/Enemy/ProtoEnemyManager.cs, MS_Project/Assets/Scripts/Character/Enemy/ProtoEnemyStatusManager.cs, MS_Project/Assets/Scripts/Character/StatusManager.cs, MS_Project/Assets/Scripts/Data/Character/CharaStatusData.cs, MS_Project/Assets/Scripts/Data/Character/Enemy/EnemyStatusData.cs
=> Update: 敵ステータスデータ更新

MS_Project/Assets/Data/Character/Enemy/EnemyStatusData.asset, MS_Project/Assets/Resources/Player/PAttack_Clip.anim, MS_Project/Assets/Scenes/SampleScene.unity, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs
=> Update: プレイヤー攻撃処理

MS_Project/Assets/Scenes/SampleScene.unity
=> Test:マージテスト

MS_Project/Assets/Model/01_Virus/Anim/attack.anim, MS_Project/Assets/Model/01_Virus/Anim/attack.anim.meta, MS_Project/Assets/Model/01_Virus/Anim/hurt.anim, MS_Project/Assets/Model/01_Virus/Anim/hurt.anim.meta, MS_Project/Assets/Model/01_Virus/Anim/idle.anim, MS_Project/Assets/Model/01_Virus/Anim/idle.anim.meta, MS_Project/Assets/Model/01_Virus/Anim/swing.anim, MS_Project/Assets/Model/01_Virus/Anim/swing.anim.meta, MS_Project/Assets/Model/01_Virus/Anim/virus_anim.controller, MS_Project/Assets/Model/01_Virus/Anim/virus_anim.controller.meta, MS_Project/Assets/Scenes/SampleScene.unity
=> 待機アニメーション適応

MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/PlayerAnimManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerStatusManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerIdleState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerStateManager.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs.meta
=> Add: 攻撃時コライダーディテクター

MS_Project/Assets/Model/01_Virus/Anim/virus_anim.controller, MS_Project/Assets/Prefabs/Enemy/Virus.prefab, MS_Project/Assets/Prefabs/Enemy/Virus.prefab.meta, MS_Project/Assets/Scripts/Data/Character/Enemy/EnemyHurt.cs, MS_Project/Assets/Scripts/Data/Character/Enemy/EnemyHurt.cs.meta
=> ウイルスが接触すると消えるよう設定&プレハブ化

MS_Project/Assets/Resources/Player/PAttack_Clip.anim, MS_Project/Assets/Resources/Player/proto_sword1.png.meta, MS_Project/Assets/Resources/Player/proto_sword2.png.meta
=> Update: プレイヤー攻撃アニメーション

MS_Project/Assets/Scripts/Data/Character/Enemy/EnemyHurt.cs
敵が消える　→　ログを出す　に変更
EnemyHurt.csを入れると反応
=> 敵がプレイヤーと接触時、ログを残すように変更

MS_Project/Assets/Resources/OnomatoEmitter.prefab, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs
=> Update: オノマトペを食べる簡易処理

MS_Project/Assets/Resources/Onomatopoeia/OnomatoItem.prefab, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Enemy/ProtoEnemyController.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerModeChangeState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerModeChangeState.cs.meta, MS_Project/Assets/Scripts/Character/Player/State/PlayerStateManager.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Onomato/OnomatoManager.cs, MS_Project/Assets/Scripts/Onomato/OnomatoManager.cs.meta, MS_Project/Assets/Scripts/Onomato/OnomatopoeiaHandler.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs, MS_Project/Assets/Scripts/Utilities/Enums.cs
=> Update: 食べてモードチェンジする処理

MS_Project/.vsconfig, MS_Project/Assets/Resources/OnomatoEmitter.prefab.meta, MS_Project/Assets/Resources/Onomatopoeia/OnomatoHammer.prefab, MS_Project/Assets/Resources/Onomatopoeia/OnomatoHammer.prefab.meta, MS_Project/Assets/Resources/Onomatopoeia/OnomatoSword.prefab, MS_Project/Assets/Resources/Onomatopoeia/OnomatoSword.prefab.meta, MS_Project/Assets/TextMesh Pro/Resources.meta
=> 剣とハンマーのオノマトペ追加

MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/State/PlayerDeadState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerDeadState.cs.meta, MS_Project/Assets/Scripts/Character/Player/State/PlayerHitState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerHitState.cs.meta, MS_Project/Assets/Scripts/Character/Player/State/PlayerStateManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerWalkState.cs
=> Add: プレイヤー被撃、死亡状態

MS_Project/Assets/Resources/Player/Player.prefab
=> Update: プレイヤープレハブに変更を適用

MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Onomato/OnomatoManager.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs
=> Update: 捕食方向補正処理

MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Onomato/OnomatoManager.cs
=> Add: 仮の暴走処理

MS_Project/Assets/Resources/Player/PAttack_Clip.anim, MS_Project/Assets/Resources/Player/PEat_Clip.anim, MS_Project/Assets/Resources/Player/PHammerAttack_Clip.anim, MS_Project/Assets/Scripts/Character/Player/PlayerAnimManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerStateManager.cs, MS_Project/Assets/Scripts/Onomato/OnomatoManager.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs
Update: 当たり判定コード整理
Add: 攻撃アニメーションイベント
=> Update: 当たり判定コード整理

.gitignore, MS_Project/Assets/Resources/Onomatopoeia/OnomatoItem.prefab, MS_Project/Assets/Scripts/Data/Onomatopoeia/OnomatopoeiaData.cs, MS_Project/Assets/Scripts/Onomatopoeia/OnomatoManager.cs, MS_Project/Assets/Scripts/Onomatopoeia/OnomatopoeiaController.cs
* 飛び出し処理を変更
* 一定時間経過後、地面に落ちるを追加
* カメラと同じ方向に向いている処理を追加
=> オノマトペ更新処理を修正

MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerDeadState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerHitState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerIdleState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerModeChangeState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerSkillState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerStateManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerWalkState.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Shaders/S_SpriteShadow.shader
* シェーダーの`ZTest`をランタイムで有効・無効に切替
* 攻撃系ステートのみに`ZTest`を有効に初期化
=> 2Dキャラ描画順を変更

MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerIdleState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerWalkState.cs
=> Fix: 連続攻撃する時、動かないバグ修正

MS_Project/Assets/Scripts/Character/Enemy/EnemyController.cs, MS_Project/Assets/Scripts/Onomatopoeia/OnomatoManager.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs, MS_Project/Assets/Scripts/Utilities/IHit.cs
=> Update: IHitに敵を一撃で倒すフラグ追加

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset.meta, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scenes/SampleScene.unity, MS_Project/Assets/Scripts/Character/Player/PlayerModeManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs.meta, MS_Project/Assets/Scripts/Character/Player/State/PlayerSkillState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerState.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerSkillData.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerSkillData.cs.meta, MS_Project/Assets/Scripts/Data/Character/Player/PlayerStatusData.cs, MS_Project/Assets/Scripts/Utilities/Enums.cs
Add: スキル管理ビヘイビア
Update: UIをプレイヤーに適用
=> Add: スキル管理ビヘイビア

MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/PlayerStatusManager.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Character/StatusManager.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerStatusData.cs
=> Update: 暴走処理コード整理

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/PlayerModeManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerIdleState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerSkillState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerWalkState.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs
=> Update: スキルと捕食、クールタイム実装

MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/PlayerStatusManager.cs, MS_Project/Assets/Scripts/Character/StatusManager.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerSkillData.cs, MS_Project/Assets/kudo/PlayerHPBar.cs
=> Update: HP更新処理

MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/PlayerStatusManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerIdleState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerWalkState.cs
=> Update: 暴走時の捕食処理

MS_Project/Assets/Resources/Player/PAttack_Clip.anim, MS_Project/Assets/Scenes/SampleScene.unity
=> Update: 攻撃アニメーション速度調整

MS_Project/Assets/Scripts/Character/PlayerController.cs
=> Fix: プレイヤーの向き修正

MS_Project/Assets/Resources/Player/Player.prefab
1.PlayerPrefabにAttackManagerの
EmptyObjectを追加
2.cameraBasedHitCorrectionをアタッチ
3.PlayerPrefabをOverride
=> fix MissingObject

MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs
=> Update: 一旦コメントアウト

MS_Project/Assets/Data/Character/Enemy/DataOther.asset, MS_Project/Assets/Data/Character/Enemy/DataOther.asset.meta, MS_Project/Assets/Data/Onomatopoeia/OnomatoDataOther.asset, MS_Project/Assets/Data/Onomatopoeia/OnomatoDataOther.asset.meta, MS_Project/Assets/Resources/Onomatopoeia/OnomatoItem.prefab, MS_Project/Assets/Scripts/Character/Enemy/EnemyController.cs, MS_Project/Assets/Scripts/Onomatopoeia/OnomatopoeiaController.cs, MS_Project/Assets/Scripts/Utilities/Enums.cs
=> オノマトペの動的生成を修正

MS_Project/Assets/Input/InputControls.cs, MS_Project/Assets/Input/InputControls.inputactions, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerIdleState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerWalkState.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Manager/Input/PlayerInputManager.cs, MS_Project/Assets/Scripts/Utilities/BlockDetector.cs, MS_Project/Assets/Scripts/Utilities/BlockDetector.cs.meta, MS_Project/ProjectSettings/TagManager.asset
=> Add: プレイヤーの回避移動処理

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerSkillData.cs, MS_Project/Assets/Scripts/Utilities/BlockDetector.cs, MS_Project/Assets/Scripts/Utilities/Enums.cs
=> Update: スキルパラメータ調整

MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/PlayerAnimManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerDodgeState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerDodgeState.cs.meta, MS_Project/Assets/Scripts/Character/Player/State/PlayerStateManager.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerSkillData.cs, MS_Project/Assets/Scripts/Manager/Input/PlayerInputManager.cs
=> Add: 回避ステート

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/DashHandler.cs, MS_Project/Assets/Scripts/Character/Player/DashHandler.cs.meta, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerDodgeState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Utilities/BlockDetector.cs
=> Update: 回避処理のコード整理

MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemySkill.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemySkills/VR_Attack.cs, MS_Project/Assets/Scripts/Data/Character/WorldObjects/EnemyStatusData.cs, MS_Project/Assets/Scripts/Utilities/IHit.cs, MS_Project/Assets/kudo/PlayerHPBar.cs
=> `player`の情報を`EnemySkill`に渡す

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Resources/Player/PAttack_Clip.anim, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/DashHandler.cs, MS_Project/Assets/Scripts/Character/Player/PlayerAnimManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerDodgeState.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerSkillData.cs, MS_Project/Assets/Scripts/Utilities/Enums.cs
=> Fix: 回避移動距離修正

MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs
=> `Collider`を`Sphere`に変更

MS_Project/Assets/Resources/Enemy/Chicken.prefab, MS_Project/Assets/Resources/Enemy/Diabolos.prefab, MS_Project/Assets/Resources/Enemy/EnemyContainer.prefab, MS_Project/Assets/Resources/Enemy/Hunter.prefab, MS_Project/Assets/Resources/Enemy/Virus.prefab, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs
=> `collider`を修正

MS_Project/Assets/Resources/Player/PSwordSkill.anim, MS_Project/Assets/Resources/Player/PSwordSkill.anim.meta, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Resources/Player/Sprite_ACont.controller, MS_Project/Assets/Scripts/Character/Player/DetectArea.cs, MS_Project/Assets/Scripts/Character/Player/DetectArea.cs.meta, MS_Project/Assets/Scripts/Character/Player/DetectEnemyArea.cs, MS_Project/Assets/Scripts/Character/Player/DetectEnemyArea.cs.meta, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerStatusManager.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs
Add: 仮のフィニッシュスキル処理
Update: 剣のスキルの仮処理
=> Update: 剣のスキルの仮処理

MS_Project/Assets/Scripts/Character/WorldObjects/ObjectStatusHandler.cs, MS_Project/Assets/Scripts/Utilities/EnemySpawner.cs
=> スポナーの`null`バグを修正

MS_Project/Assets/Fantasy Adventure Environment/Shaders/URP/_UniversalRenderPipeline.unitypackage.meta, MS_Project/Assets/Scripts/Editor/StageEditorWindow.cs, MS_Project/Assets/Scripts/Editor/StageEditorWindow.cs.meta
=> add EditorWindow

MS_Project/Assets/Data/Character/Player/PlayerStatusData.asset, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/PlayerStatusManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerWalkState.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs
=> Fix: プレイヤー移動速度調整機能修正

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Data/Character/Player/PlayerStatusData.asset, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/DashHandler.cs, MS_Project/Assets/Scripts/Character/Player/DetectEnemyArea.cs, MS_Project/Assets/Scripts/Character/Player/PlayerAnimManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerStatusManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerFinishState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerFinishState.cs.meta, MS_Project/Assets/Scripts/Character/Player/State/PlayerIdleState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerSkillState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerStateManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerWalkState.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Manager/Input/PlayerInputManager.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs
Fix: 突進時の向き修正
Add: プレイヤーのフィニッシュスキル状態
=> Add: プレイヤーのフィニッシュスキル状態

MS_Project/Assets/Scripts/Character/Player/DetectEnemyArea.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Character/StatusManager.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs
Add: 敵側のヒットストップ仮処理
Update: 敵が被弾時のアニメーション調整(0フレームから)
Add: isKillableゲッター
=> Add: 敵側のヒットストップ仮処理

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Data/Character/Player/PlayerStatusData.asset, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerIdleState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerStateManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerWalkState.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs
=> Update: 回避遷移コード整理

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Resources/Player/PSpearAttack.anim, MS_Project/Assets/Resources/Player/PSpearSkill.anim, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/PlayerModeManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Onomatopoeia/OnomatoManager.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs, MS_Project/Assets/kudo/PlayerRage.cs
Update: アニメーション調整
Update: オノマトペ食べる処理のコード整理
=> Update: アニメーション調整

MS_Project/Assets/Rendering.meta, MS_Project/Assets/Rendering/CustomPostProcessProfile.asset, MS_Project/Assets/Rendering/CustomPostProcessProfile.asset.meta, MS_Project/Assets/Rendering/PPCrossHatching.cs, MS_Project/Assets/Rendering/PPCrossHatching.cs.meta, MS_Project/Assets/Rendering/PPGrayscale.cs, MS_Project/Assets/Rendering/PPGrayscale.cs.meta, MS_Project/Assets/Rendering/PPHalftone.cs, MS_Project/Assets/Rendering/PPHalftone.cs.meta, MS_Project/Assets/Resources/Materials/M_CrossHatchPP.mat, MS_Project/Assets/Resources/Materials/M_CrossHatchPP.mat.meta, MS_Project/Assets/Resources/Materials/M_ProceduralCrossHatch.mat, MS_Project/Assets/Resources/Materials/M_ProceduralCrossHatch.mat.meta, MS_Project/Assets/Scenes/SampleScene.unity, MS_Project/Assets/Scripts/Shaders/PPS_CrossHatch.shader, MS_Project/Assets/Scripts/Shaders/PPS_CrossHatch.shader.meta, MS_Project/Assets/Scripts/Shaders/PPS_Grayscale.shader, MS_Project/Assets/Scripts/Shaders/PPS_Grayscale.shader.meta, MS_Project/Assets/Scripts/Shaders/PPS_Halftone.shader, MS_Project/Assets/Scripts/Shaders/PPS_Halftone.shader.meta, MS_Project/ProjectSettings/TagManager.asset
* カメラ用 grayscale, cross hatch, halftoneを追加
* ポストエフェクト用レイヤー追加
* レイヤー順番調整
=> ポストエフェクト処理を追加

MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/State/PlayerSkillState.cs
=> Fix: 長押し当たり判定

MS_Project/Assets/Resources/Player/PSwordSkill.anim, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerDodgeState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerIdleState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerSkillState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerStateManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerWalkState.cs
Update: ステートコード整理
Add: ステートのキャンセル処理
=> Update: ステートコード整理

MS_Project/Assets/Resources/Player/PAttack_Clip.anim, MS_Project/Assets/Resources/Player/PGauntletAttack.anim, MS_Project/Assets/Resources/Player/PSwordSkill.anim, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/Bullet/Bullet.cs, MS_Project/Assets/Scripts/Character/Player/PlayerAnimManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerSkillState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerStateManager.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs
=> Fix: 捕食処理修正

MS_Project/Assets/Resources/Player/Player.prefab
=> Update: プレイヤースキル範囲調整

MS_Project/Assets/Scripts/Character/WorldObjects/ObjectController.cs, MS_Project/Assets/Scripts/Onomatopoeia/OnomatopoeiaController.cs
=> オノマトペの`Quarternion`回転を修正

MS_Project/Assets/Scripts/Character/Player/DashHandler.cs
=> Fix: オノマトペとプレイヤーの当たり判定を無くす

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Scripts/Character/Player/PlayerModeManager.cs
=> Update: スキルのHP消費

MS_Project/Assets/Resources/Player/Player.prefab
=> Update: デフォルトモードを剣に設定

MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerSkillState.cs
=> Update: 暴走時ダメージ5倍にする仮処理

MS_Project/Assets/Model/07_Giant/Anim/AnimCont_Giant.controller, MS_Project/Assets/Scenes/SampleScene.unity
攻撃方法がわかってしまったかもしれない( ͡° ͜ʖ ͡°)
=> 巨人を攻撃させるようにした

MS_Project/Assets/Data/Character/Player/PlayerHitData.asset, MS_Project/Assets/Data/Character/Player/PlayerHitData.asset.meta, MS_Project/Assets/Scenes/Objects/Manager.prefab, MS_Project/Assets/Scenes/SampleScene.unity, MS_Project/Assets/Scripts/Character/Player/PlayerModeManager.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerHitData.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerHitData.cs.meta, MS_Project/Assets/Scripts/Manager/BattleManager.cs, MS_Project/Assets/Scripts/Manager/BattleManager.cs.meta, MS_Project/ProjectSettings/TimelineSettings.asset
Add: バトルマネージャー(ヒットストップなどを管理する)
=> Add: バトルマネージャー(ヒットストップなどを管理する)

MS_Project/Assets/Data/Character/Player/PlayerHitData.asset, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs, MS_Project/Assets/Scripts/Manager/BattleManager.cs
=> Update: ヒットストップコードのリファクタリング

MS_Project/Assets/Data/Character/WorldObjects/Boss_Diabolos.asset, MS_Project/Assets/Data/Character/WorldObjects/Elite_Giant.asset, MS_Project/Assets/Data/Character/WorldObjects/Elite_Hunter.asset, MS_Project/Assets/Data/Character/WorldObjects/Enemy_Chicken.asset, MS_Project/Assets/Data/Character/WorldObjects/Enemy_UFO.asset, MS_Project/Assets/Data/Character/WorldObjects/Enemy_Virus.asset, MS_Project/Assets/Resources/Enemy/BaseEnemy.prefab, MS_Project/Assets/Resources/Enemy/BaseEnemy.prefab.meta, MS_Project/Assets/Resources/Enemy/ChickenV2.prefab, MS_Project/Assets/Resources/Enemy/ChickenV2.prefab.meta, MS_Project/Assets/Resources/Enemy/DiabolosV2.prefab, MS_Project/Assets/Resources/Enemy/DiabolosV2.prefab.meta, MS_Project/Assets/Resources/Enemy/GiantV2.prefab, MS_Project/Assets/Resources/Enemy/GiantV2.prefab.meta, MS_Project/Assets/Resources/Enemy/HunterV2.prefab, MS_Project/Assets/Resources/Enemy/HunterV2.prefab.meta, MS_Project/Assets/Resources/Enemy/UFOV2.prefab, MS_Project/Assets/Resources/Enemy/UFOV2.prefab.meta, MS_Project/Assets/Resources/Enemy/VirusV2.prefab, MS_Project/Assets/Resources/Enemy/VirusV2.prefab.meta
Update: 生成する敵の差し替え
Add: 親がある敵プレハブ追加
=> Add: 親がある敵プレハブ追加

MS_Project/Assets/Resources/Enemy/EnemyContainer.prefab, MS_Project/Assets/Resources/Enemy/HunterV2.prefab, MS_Project/Assets/Resources/Enemy/VirusV2.prefab, MS_Project/Assets/Scripts/Character/Player/DashHandler.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Character/WorldObject.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectController.cs
=> Fix: 敵hpbar参照バグ修正

MS_Project/Assets/Model/03_Hunter/Anim/run_HN.anim, MS_Project/Assets/Resources/Enemy/BaseEnemy.prefab, MS_Project/Assets/Resources/Enemy/EnemyContainer.prefab, MS_Project/Assets/Scripts/Character/Player/DashHandler.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyAnimManager.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemySkillManager.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemySkillManager.cs.meta
=> Update: 敵アニメーションイベント仮処理

MS_Project/Assets/Scripts/Character/Player/DashHandler.cs, MS_Project/Assets/Scripts/Character/Player/PlayerAnimManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyAnimManager.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemySkillManager.cs
Update: DashStart関数名衝突のため、変更する
=> Update: DashStart関数名衝突のため、変更する

MS_Project/Assets/Model/03_Hunter/Anim/run_HN.anim, MS_Project/Assets/Resources/Effect/HitEffect.prefab, MS_Project/Assets/Resources/Enemy/BaseEnemy.prefab, MS_Project/Assets/Resources/Enemy/DiabolosV2.prefab, MS_Project/Assets/Resources/Enemy/GiantV2.prefab, MS_Project/Assets/Resources/Enemy/HunterV2.prefab, MS_Project/Assets/Resources/Enemy/UFOV2.prefab, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyEffectManager.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyEffectManager.cs.meta
Update: エフェクトサイズ調整
Add: 敵エフェクトマネージャー
=> Update: エフェクト生成位置調整

MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Character/WorldObject.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyEffectManager.cs
Add: WorldObject前方向取得関数
Update: EnemyEffectManagerを他のオブジェクトも使えるように
=> Add: WorldObject前方向取得関数

MS_Project/Assets/Resources/Others/HitCollider.prefab, MS_Project/Assets/Resources/Others/HitCollider.prefab.meta, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/DetectEnemyArea.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManager.cs, MS_Project/Assets/Scripts/Utilities/HitCollider.cs, MS_Project/Assets/Scripts/Utilities/HitCollider.cs.meta
Add: 新しい当たり判定用コライダー　
Update: プレイヤーの前方向を変更できるように
=> Add: 新しい当たり判定用コライダー　

MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerFinishState.cs
=> Update: いらないコードを消す

MS_Project/Assets/Scripts/Utilities/AttackColliderManagerV2.cs
Fix: CameraBasedHitCorrection取得
=> Fix: CameraBasedHitCorrection取得

MS_Project/Assets/Data/Character/Player/PlayerStatusData.asset, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerStatusData.cs
Update: Dataで各モードの攻撃力を調整できるように
=> Update: Dataで各モードの攻撃力を調整できるように

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/State/PlayerSkillState.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerSkillData.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManagerV2.cs
Update: スキルダメージを調整できるように
Fix: カメラベースの当たり判定補正を適用
=> Update: スキルダメージを調整できるように

MS_Project/Assets/Scripts/Character/Player/State/PlayerSkillState.cs
=> Fix: ハンマースキル範囲拡大修正

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Resources/Player/PGauntletSkill.anim, MS_Project/Assets/Scripts/Character/Player/State/PlayerSkillState.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerSkillData.cs
=> Add: パンチスキル

MS_Project/Assets/Model/04_Diabolos/DragonFireRelease.cs, MS_Project/Assets/Model/04_Diabolos/DragonFireRelease.cs.meta, MS_Project/Assets/Scenes/SampleScene.unity
=> DragonFireRelease

MS_Project/Assets/Resources/Enemy/Giant.prefab, MS_Project/Assets/Resources/Enemy/Golem.prefab, MS_Project/Assets/Resources/Enemy/HunterV2.prefab, MS_Project/Assets/Resources/Enemy/UFOV2.prefab, MS_Project/Assets/Resources/Enemy/Ultimate.prefab, MS_Project/Assets/Resources/Enemy/VirusV2.prefab, MS_Project/Assets/Scenes/SampleScene.unity
巨人、ゴーレム、ハンター、UFO、ラスボス、ウイルスにHitColiderを入れたんご
=> HitColiderを敵に付与

MS_Project/Assets/Editor/BuildApplication.cs, MS_Project/Assets/Model/03_Hunter/Anim/AnimCont_Hunter.controller, MS_Project/Assets/Model/03_Hunter/Anim/walk_HN_2.0.anim, MS_Project/Assets/Resources/Enemy/Hunter.prefab, MS_Project/Assets/Resources/Enemy/HunterV2.prefab, MS_Project/ProjectSettings/EditorBuildSettings.asset
=> ハンターのrigidbodyを修正

.github/workflows/main.yml, MS_Project/Assets/Editor/BuildApplication.cs, MS_Project/Assets/Resources/Enemy/GiantV2.prefab, MS_Project/Assets/Scripts/Utilities/Collector.cs
=> 消えたGiantを元に戻す

MS_Project/Assets/Scripts/Character/Player/PlayerAnimManager.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Character/WorldObject.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManagerV2.cs, MS_Project/Assets/Scripts/Utilities/IMiss.cs, MS_Project/Assets/Scripts/Utilities/IMiss.cs.meta
Add: 空振り処理のインターフェース
Update: プレイヤーの空振り処理
=> Add: 空振り処理のインターフェース

MS_Project/Assets/Data/Character/WorldObjects/Boss_Golem.asset, MS_Project/Assets/Data/Character/WorldObjects/Boss_Golem.asset.meta, MS_Project/Assets/Model/07_Golem/Anim/AnimCont_Golem.controller, MS_Project/Assets/Resources/Enemy/GolemV2.prefab, MS_Project/Assets/Resources/Enemy/GolemV2.prefab.meta, MS_Project/Assets/Scenes/SampleScene.unity
=> EnemyGolem_BossHp

MS_Project/Assets/Scripts/Camera/CameraController.cs
=> Fix camera

MS_Project/Assets/Resources/Enemy/EnemySpawner.prefab, MS_Project/Assets/Resources/UI/InGameUI.prefab, MS_Project/Assets/Scripts/Character/WorldObjects/EnemySpawner.cs, MS_Project/Assets/Scripts/UI/UIMissionController.cs
=> エネミーが生成しないことを修正

MS_Project/Assets/Data/Character/WorldObjects/Enemy_Virus_nega.asset, MS_Project/Assets/Data/Character/WorldObjects/Enemy_Virus_sweet.asset, MS_Project/Assets/Resources/Enemy/BaseEnemy.prefab, MS_Project/Assets/Resources/Enemy/ChickenV2.prefab, MS_Project/Assets/Resources/Enemy/GiantV2.prefab, MS_Project/Assets/Resources/Enemy/HunterV2.prefab, MS_Project/Assets/Resources/Enemy/KnightV2.prefab, MS_Project/Assets/Resources/Enemy/UFOV2.prefab, MS_Project/Assets/Resources/Enemy/VirusV2.prefab, MS_Project/Assets/Resources/Enemy/Virus_negaV2.prefab, MS_Project/Assets/Resources/Enemy/Virus_sweetV2.prefab
Update: アニメーションマネージャーをアニメーターのところに移動させる
Update: sweetとnegaの生成をV2に変更した
=> Update: アニメーションマネージャーをアニメーターのところに移動させる

MS_Project/Assets/Resources/Enemy/ChickenV2.prefab, MS_Project/Assets/Resources/Enemy/GiantV2.prefab, MS_Project/Assets/Resources/Enemy/HunterV2.prefab, MS_Project/Assets/Resources/Enemy/KnightV2.prefab, MS_Project/Assets/Resources/Enemy/UFOV2.prefab, MS_Project/Assets/Resources/Enemy/VirusV2.prefab, MS_Project/Assets/Resources/Enemy/Virus_negaV2.prefab, MS_Project/Assets/Resources/Enemy/Virus_sweetV2.prefab, MS_Project/Assets/Resources/Others/EnemyAttackCollider.prefab, MS_Project/Assets/Resources/Others/EnemyAttackCollider.prefab.meta
Add: 敵用攻撃コライダー
Update: 敵攻撃コライダーのレイヤー変更
=> Add: 敵用攻撃コライダー

MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Resources/Player/PEat_Clip.anim, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerSkillData.cs
Update: スキルのヒットストップ処理
Update: 捕食アニメーションの速度調整
=> Update: スキルのヒットストップ処理

MS_Project/Assets/Data/Character/Player/PlayerHitData.asset, MS_Project/Assets/Data/Character/Player/PlayerSkillData.asset, MS_Project/Assets/Resources/Player/PEat_Clip.anim, MS_Project/Assets/Resources/Player/Player.prefab, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerEatState.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Manager/BattleManager.cs
Update: プレイヤーパラメータ調整
Fix: ヒットストップバグ修正
=> Update: プレイヤーパラメータ調整

MS_Project/Assets/Model/03_Hunter/AIHunter.cs, MS_Project/Assets/Model/03_Hunter/AIHunter.cs.meta, MS_Project/Assets/Model/03_Hunter/Anim/AnimCont_Hunter.controller, MS_Project/Assets/Model/03_Hunter/Anim/run_HN.anim, MS_Project/Assets/Model/03_Hunter/Anim/throw_HN.anim, MS_Project/Assets/Model/07_Golem/Anim/AnimCont_Golem.controller, MS_Project/Assets/Model/08_Giant/Anim/AnimCont_Giant.controller, MS_Project/Assets/Model/08_Giant/Anim/dash_GI.anim, MS_Project/Assets/Resources/Enemy/HunterV2.prefab
斧も投げます
ちゃんと稼働してないので直そう
enemyactionでNULLってる
=> ハンターAI追加&アニメーター修正

MS_Project/Assets/Model/03_Hunter/AIHunter_ThrowAxe.cs, MS_Project/Assets/Model/03_Hunter/Anim/attack_HN.anim, MS_Project/Assets/Resources/Enemy/HunterV2.prefab, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyAction.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyAnimManager.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemySkills/HunterAction.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemySkills/HunterAction.cs.meta, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectStates/ObjectStateHandler.cs, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectStates/StateAttack.cs, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectStates/StateSkill.cs, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectStates/StateWalk.cs
Add: HunterAction.cs ハンターAI
Update: ハンター攻撃判定アニメーションイベント
Update: ステートの独自処理
=> Add: HunterAction.cs ハンターAI

MS_Project/Assets/Resources/UI/InGameUI.prefab, MS_Project/Assets/Resources/UI/MissionPanel.controller, MS_Project/Assets/Resources/UI/MissionPanel.controller.meta, MS_Project/Assets/Resources/UI/MissionTitle.controller, MS_Project/Assets/Resources/UI/MissionTitle.controller.meta, MS_Project/Assets/Resources/UI/UIMissionPanel.anim, MS_Project/Assets/Resources/UI/UIMissionPanel.anim.meta, MS_Project/Assets/Resources/UI/UIMissionTitle.anim, MS_Project/Assets/Resources/UI/UIMissionTitle.anim.meta, MS_Project/Assets/Scripts/Character/WorldObjects/EnemySpawner.cs, MS_Project/Assets/Scripts/UI/UIMissionController.cs, MS_Project/Assets/Scripts/Utilities/Enums.cs
=> スポナー起動と繋がっているミッション

MS_Project/Assets/Scenes/Result.unity, MS_Project/Assets/Scenes/Result.unity.meta, MS_Project/Assets/Scripts/UI/ResultUI/GoToResult.cs, MS_Project/Assets/Scripts/UI/ResultUI/GoToResult.cs.meta, MS_Project/Assets/Scripts/UI/ResultUI/UIGameManager.cs, MS_Project/Assets/Scripts/UI/ResultUI/UIGameManager.cs.meta, MS_Project/Assets/Scripts/UI/ResultUI/UIResultManager.cs, MS_Project/Assets/Scripts/UI/ResultUI/UIResultManager.cs.meta, MS_Project/Assets/Scripts/UI/ResultUI/UISceneChange.cs, MS_Project/Assets/Scripts/UI/ResultUI/UISceneChange.cs.meta
仮ResultUIの追加(Result画面->Title画面のみ)
=> ResultUIを追加しました

MS_Project/Assets/Resources/Others/CameraPivot.prefab, MS_Project/Assets/Scripts/Camera/CameraInputHandler.cs, MS_Project/Assets/Scripts/Camera/CameraInputHandler.cs.meta, MS_Project/Assets/Scripts/Camera/Setting/CameraLockOnSettings.cs, MS_Project/Assets/Scripts/Camera/Setting/CameraLockOnSettings.cs.meta, MS_Project/Assets/Scripts/Camera/Setting/CameraSettings.cs, MS_Project/Assets/Scripts/Camera/Setting/CameraStateSettings.cs, MS_Project/Assets/Scripts/Camera/Setting/CameraStateSettings.cs.meta, MS_Project/Assets/Scripts/Camera/State/CameraLockOnState.cs, MS_Project/Assets/Scripts/Camera/State/CameraLockOnState.cs.meta
*cameraInputHandlerを追加
*LockOnステートを追加
*Lockon設定追加
=> add cameraステート

MS_Project/Assets/Fantasy Adventure Environment/Shaders/URP/_UniversalRenderPipeline.unitypackage.meta, MS_Project/Assets/Plugins/Pixel Crushers/Scene Streamer/Example/ExampleMaterials_URP.unitypackage.meta, MS_Project/Assets/Plugins/Pixel Crushers/Scene Streamer/Scripts/SceneStreamer.cs, MS_Project/Assets/Scenes/minimap.unity, MS_Project/Assets/Scenes/minimap.unity.meta, MS_Project/Assets/Scripts/Map/MapManager.cs, MS_Project/Assets/Scripts/Map/MinimapUIController.cs, MS_Project/Assets/Scripts/Map/MinimapUIController.cs.meta
*mapUIController追加
*MapManagerを更新
=> add minimap

MS_Project/Assets/Resources/Enemy/HunterV2LIST.prefab, MS_Project/Assets/Resources/Enemy/HunterV2LIST.prefab.meta, MS_Project/Assets/Scripts/Character/WorldObjects/ActionPatternList.cs, MS_Project/Assets/Scripts/Character/WorldObjects/ActionPatternList.cs.meta, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyAction.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemySkills/HunterActionList.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemySkills/HunterActionList.cs.meta, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectStates/StateIdle.cs
Add: 敵行動パターンリスト
Add: リストテスト用のハンタープレハブ
=> Add: リストテスト用のハンタープレハブ

MS_Project/Assets/Model/02_Chicken/Anim/AnimCont_Chicken.controller, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs
Update: チキンのescapeアニメーションをattackに繋げる
Fix: StateHandler取得できないバグ修正
=> Update: チキンのescapeアニメーションをattackに繋げる

MS_Project/Assets/Scripts/Map/MiniMapOverall.cs, MS_Project/Assets/Scripts/Map/MiniMapSwitching.cs, MS_Project/Assets/Scripts/Stageselect/MathfUtil.cs, MS_Project/Assets/Scripts/Stageselect/RingStage.cs, MS_Project/Assets/Scripts/Utilities/ISelected.cs
=> ファイルエンコーディングをUTF8に修正

MS_Project/Assets/Resources/Enemy/EnemyContainer.prefab, MS_Project/Assets/Resources/WorldObjects/Objects/ObjectContainer.prefab, MS_Project/Assets/Resources/WorldObjects/WorldObjectContainer.prefab, MS_Project/Assets/Scripts/Character/Player/DashHandler.cs, MS_Project/Assets/Scripts/Character/WorldObjects/EnemyController.cs, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectController.cs, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectStates/ObjectState.cs, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectStates/ObjectStateHandler.cs, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectStates/StateDamaged.cs, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectStates/StateIdle.cs, MS_Project/Assets/Scripts/Character/WorldObjects/ObjectStates/StateWalk.cs, MS_Project/Assets/Scripts/Character/WorldObjects/WorldObjectController.cs, MS_Project/ProjectSettings/TagManager.asset
* オブジェクト対応に修正
* nullチェック
* 共用じゃないscriptを <ins>親Container</ins> から **子Container** に移行
* 当たり判定用レイヤー名を修正：~`Enemy`~ から`AttackableObject`
* `Enemy`と`StaticObject`タグを追加
=> ステートマシンを修正

MS_Project/Assets/Scripts/Data/Onomatopoeia/OnomatopoeiaData.cs, MS_Project/Assets/Scripts/Onomatopoeia/OnomatopoeiaController.cs
=> オノマトペ用画像サイズ調整を追加

MS_Project/Assets/Scripts/Character/Player/DashHandler.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerAttackState.cs, MS_Project/Assets/Scripts/Utilities/AttackColliderManagerV2.cs
Update: ノックバックにヒットストップの影響を適用する
Update: attackableLayer変数を無くす
=> Update: レイヤー指定なしの当たり判定関数

MS_Project/Assets/Data/Character/Player/PlayerStatusData.asset, MS_Project/Assets/Scripts/Character/Player/PlayerStatusManager.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerDodgeState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerHitState.cs, MS_Project/Assets/Scripts/Character/Player/State/PlayerStateManager.cs, MS_Project/Assets/Scripts/Character/PlayerController.cs, MS_Project/Assets/Scripts/Character/StatusManager.cs, MS_Project/Assets/Scripts/Data/Character/Player/PlayerStatusData.cs
Update: プレイヤーのisHitをstautsManagerに移動させる
=> Update: プレイヤー回避中無敵処理

MS_Project/Assets/Data/Character/Player/PlayerHitData.asset, MS_Project/Assets/Data/Character/WorldObjects/Boss_Diabolos.asset, MS_Project/Assets/Data/Character/WorldObjects/Boss_Golem.asset, MS_Project/Assets/Data/Character/WorldObjects/Boss_Ultimate.asset, MS_Project/Assets/Data/Character/WorldObjects/Elite_Giant.asset, MS_Project/Assets/Data/Character/WorldObjects/Elite_Hunter.asset, MS_Project/Assets/Data/Character/WorldObjects/Enemy_Chicken.asset, MS_Project/Assets/Data/Character/WorldObjects/Enemy_Knight.asset, MS_Project/Assets/Data/Character/WorldObjects/Enemy_UFO.asset, MS_Project/Assets/Data/Character/WorldObjects/Enemy_VirusNega.asset, MS_Project/Assets/Data/Character/WorldObjects/Enemy_VirusNormal.asset, MS_Project/Assets/Data/Character/WorldObjects/Enemy_VirusSweet.asset, MS_Project/Assets/Resources/Player/PHammerAttack_Clip.anim, MS_Project/Assets/Scripts/Character/Player/DashHandler.cs, MS_Project/Assets/Scripts/Character/Player/PlayerAnimManager.cs, MS_Project/Assets/Scripts/Character/Player/PlayerSkillManager.cs
Update: 敵ノックバックデータ調整
Update: プレイヤースキル中赤くするのを消す
Update: ハンマー攻撃にロックオン補正追加
Update: 剣とハンマーの攻撃移動距離調整
=> Fix: 攻撃中移動と攻撃補正移動の調整

MS_Project/Assets/Fantasy Adventure Environment/Shaders/URP/_UniversalRenderPipeline.unitypackage.meta, MS_Project/Assets/Plugins/Pixel Crushers/Scene Streamer/Example/ExampleMaterials_URP.unitypackage.meta, MS_Project/ProjectSettings/Packages/com.unity.testtools.codecoverage/Settings.json
*CullingMaskを修正
Camera/BasicSettings/CullingMask->EveryThing
*追従設定を修正
Camera/BasicSettings/FollowSettings/
PositionOffset
=> Fix Setting

MS_Project/Assets/Scenes/oogishi/Prefabs/Walls/Doorways/Doorway Parent 002.prefab, MS_Project/Assets/_Plugins/CFXR/CFXR Assets/Shaders/CFXR Particle Distortion.cfxrshader.meta, MS_Project/Assets/_Plugins/CFXR/CFXR Assets/Shaders/CFXR Particle Glow.cfxrshader.meta, MS_Project/Assets/_Plugins/CFXR/CFXR Assets/Shaders/CFXR Particle Procedural Ring.cfxrshader.meta, MS_Project/Assets/_Plugins/CFXR/CFXR Assets/Shaders/CFXR Particle Ubershader.cfxrshader.meta
=> Fix Broken Material
